package shell

// FILEOPENDIALOGOPTIONS specifies the options for an IFileDialog.
type FILEOPENDIALOGOPTIONS uint32

const (
	FOS_OVERWRITEPROMPT    FILEOPENDIALOGOPTIONS = 0x2
	FOS_STRICTFILETYPES    FILEOPENDIALOGOPTIONS = 0x4
	FOS_NOCHANGEDIR        FILEOPENDIALOGOPTIONS = 0x8
	FOS_PICKFOLDERS        FILEOPENDIALOGOPTIONS = 0x20
	FOS_FORCEFILESYSTEM    FILEOPENDIALOGOPTIONS = 0x40
	FOS_ALLNONSTORAGEITEMS FILEOPENDIALOGOPTIONS = 0x80
	FOS_NOVALIDATE         FILEOPENDIALOGOPTIONS = 0x100
	FOS_ALLOWMULTISELECT   FILEOPENDIALOGOPTIONS = 0x200
	FOS_PATHMUSTEXIST      FILEOPENDIALOGOPTIONS = 0x800
	FOS_FILEMUSTEXIST      FILEOPENDIALOGOPTIONS = 0x1000
	FOS_CREATEPROMPT       FILEOPENDIALOGOPTIONS = 0x2000
	FOS_SHAREAWARE         FILEOPENDIALOGOPTIONS = 0x4000
	FOS_NOREADONLYRETURN   FILEOPENDIALOGOPTIONS = 0x8000
	FOS_NOTESTFILECREATE   FILEOPENDIALOGOPTIONS = 0x10000
	FOS_HIDEMRUPLACES      FILEOPENDIALOGOPTIONS = 0x20000
	FOS_HIDEPINNEDPLACES   FILEOPENDIALOGOPTIONS = 0x40000
	FOS_NODEREFERENCELINKS FILEOPENDIALOGOPTIONS = 0x100000
	FOS_DONTADDTORECENT    FILEOPENDIALOGOPTIONS = 0x2000000
	FOS_FORCESHOWHIDDEN    FILEOPENDIALOGOPTIONS = 0x10000000
)

// SIGDN specifies the display name for IShellItem.GetDisplayName.
type SIGDN uint32

const (
	SIGDN_NORMALDISPLAY          SIGDN = 0
	SIGDN_FILESYSPATH            SIGDN = 0x80058000
	SIGDN_DESKTOPABSOLUTEPARSING SIGDN = 0x80028000
)

// COMDLG_FILTERSPEC defines a file type filter for IFileDialog.SetFileTypes.
type COMDLG_FILTERSPEC struct {
	Name *uint16 // LPCWSTR display name, e.g. "Images"
	Spec *uint16 // LPCWSTR pattern list, e.g. "*.png;*.jpg"
}
